/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  web3,
  Contract as ContractArtifact,
  SignerProvider,
  Address,
  Token,
  toApiVals,
  ContractState,
  node,
  binToHex,
  TestContractResult,
  InputAsset,
  Asset,
  SignDeployContractTxResult,
  contractIdFromAddress,
  fromApiArray,
} from "@alephium/web3";

export namespace MetaData {
  export type State = Omit<ContractState, "fields">;

  export async function deploy(
    signer: SignerProvider,
    deployParams?: {
      initialAttoAlphAmount?: bigint;
      initialTokenAmounts?: Token[];
      issueTokenAmount?: bigint;
      gasAmount?: number;
      gasPrice?: bigint;
    }
  ): Promise<Contract> {
    const deployResult = await artifact.deploy(signer, {
      initialFields: {},
      initialAttoAlphAmount: deployParams?.initialAttoAlphAmount,
      initialTokenAmounts: deployParams?.initialTokenAmounts,
      issueTokenAmount: deployParams?.issueTokenAmount,
      gasAmount: deployParams?.gasAmount,
      gasPrice: deployParams?.gasPrice,
    });
    return new Contract(
      deployResult.contractAddress,
      deployResult.contractId,
      deployResult.fromGroup,
      deployResult
    );
  }

  export function attach(
    address: string,
    deployResult?: SignDeployContractTxResult
  ): Contract {
    const contractId = binToHex(contractIdFromAddress(address));
    const groupIndex = parseInt(contractId.slice(-2));
    return new Contract(address, contractId, groupIndex, deployResult);
  }

  export class Contract {
    readonly address: Address;
    readonly contractId: string;
    readonly groupIndex: number;
    deployResult: SignDeployContractTxResult | undefined;

    constructor(
      address: Address,
      contractId: string,
      groupIndex: number,
      deployResult?: SignDeployContractTxResult
    ) {
      this.address = address;
      this.contractId = contractId;
      this.groupIndex = groupIndex;
      this.deployResult = deployResult;
    }

    async fetchState(): Promise<State> {
      const state = await artifact.fetchState(this.address, this.groupIndex);
      return {
        ...state,
      };
    }

    // This is used for testing contract functions
    static stateForTest(asset?: Asset, address?: string): ContractState {
      const newAsset = {
        alphAmount: asset?.alphAmount ?? BigInt(1000000000000000000),
        tokens: asset?.tokens,
      };
      return artifact.toState({}, newAsset, address);
    }

    static async testFooMethod(testParams?: {
      group?: number;
      address?: string;
      initialAsset?: Asset;
      existingContracts?: ContractState[];
      inputAssets?: InputAsset[];
    }): Promise<Omit<TestContractResult, "returns"> & { returns: [] }> {
      const initialAsset = {
        alphAmount:
          testParams?.initialAsset?.alphAmount ?? BigInt(1000000000000000000),
        tokens: testParams?.initialAsset?.tokens,
      };
      const _testParams = {
        ...testParams,
        testMethodIndex: 0,
        testArgs: {},
        initialFields: {},
        initialAsset: initialAsset,
      };
      const testResult = await artifact.testPublicMethod("foo", _testParams);
      return { ...testResult, returns: testResult.returns as [] };
    }

    static async testBarMethod(testParams?: {
      group?: number;
      address?: string;
      initialAsset?: Asset;
      existingContracts?: ContractState[];
      inputAssets?: InputAsset[];
    }): Promise<Omit<TestContractResult, "returns"> & { returns: [] }> {
      const initialAsset = {
        alphAmount:
          testParams?.initialAsset?.alphAmount ?? BigInt(1000000000000000000),
        tokens: testParams?.initialAsset?.tokens,
      };
      const _testParams = {
        ...testParams,
        testMethodIndex: 1,
        testArgs: {},
        initialFields: {},
        initialAsset: initialAsset,
      };
      const testResult = await artifact.testPrivateMethod("bar", _testParams);
      return { ...testResult, returns: testResult.returns as [] };
    }

    static async testBazMethod(testParams?: {
      group?: number;
      address?: string;
      initialAsset?: Asset;
      existingContracts?: ContractState[];
      inputAssets?: InputAsset[];
    }): Promise<Omit<TestContractResult, "returns"> & { returns: [] }> {
      const initialAsset = {
        alphAmount:
          testParams?.initialAsset?.alphAmount ?? BigInt(1000000000000000000),
        tokens: testParams?.initialAsset?.tokens,
      };
      const _testParams = {
        ...testParams,
        testMethodIndex: 2,
        testArgs: {},
        initialFields: {},
        initialAsset: initialAsset,
      };
      const testResult = await artifact.testPrivateMethod("baz", _testParams);
      return { ...testResult, returns: testResult.returns as [] };
    }
  }

  export const artifact = ContractArtifact.fromJson(
    JSON.parse(`{
  "version": "v1.7.0",
  "name": "MetaData",
  "bytecode": "0003144027402e010300000005b4b413c40de0b6b3a7640000a702000200000004b213c40de0b6b3a7640000a90200000000000102",
  "codeHash": "cade0de390b8e15960b263ac35aa013cb84f844bce6e3e53e6bfe2cc9166623f",
  "fieldsSig": {
    "names": [],
    "types": [],
    "isMutable": []
  },
  "eventsSig": [],
  "functions": [
    {
      "name": "foo",
      "usePreapprovedAssets": true,
      "useAssetsInContract": false,
      "isPublic": true,
      "paramNames": [],
      "paramTypes": [],
      "paramIsMutable": [],
      "returnTypes": []
    },
    {
      "name": "bar",
      "usePreapprovedAssets": false,
      "useAssetsInContract": true,
      "isPublic": false,
      "paramNames": [],
      "paramTypes": [],
      "paramIsMutable": [],
      "returnTypes": []
    },
    {
      "name": "baz",
      "usePreapprovedAssets": false,
      "useAssetsInContract": false,
      "isPublic": false,
      "paramNames": [],
      "paramTypes": [],
      "paramIsMutable": [],
      "returnTypes": []
    }
  ]
}`)
  );
}
