/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  web3,
  SignerProvider,
  Address,
  toApiVals,
  DeployContractParams,
  DeployContractResult,
  Contract,
  ContractState,
  node,
  binToHex,
  TestContractResult,
  InputAsset,
  Asset,
  HexString,
  ContractFactory,
  contractIdFromAddress,
  fromApiArray,
  ONE_ALPH,
  groupOfAddress,
  fromApiVals,
  subscribeToEvents,
  SubscribeOptions,
  Subscription,
  EventSubscription,
} from "@alephium/web3";
import { default as AddContractJson } from "../add/add.ral.json";

export namespace Add {
  export type Fields = {
    sub: HexString;
    result: bigint;
  };

  export type State = Fields & Omit<ContractState, "fields">;

  export type AddEvent = {
    blockHash: string;
    txId: string;
    x: bigint;
    y: bigint;
    eventIndex: number;
  };

  export type Add1Event = {
    blockHash: string;
    txId: string;
    a: bigint;
    b: bigint;
    eventIndex: number;
  };

  export class Factory extends ContractFactory<AddInstance, Fields> {
    constructor(contract: Contract) {
      super(contract);
    }

    async deploy(
      signer: SignerProvider,
      deployParams: DeployContractParams<Fields>
    ): Promise<DeployContractResult<AddInstance>> {
      const signerParams = await contract.txParamsForDeployment(
        signer,
        deployParams
      );
      const result = await signer.signAndSubmitDeployContractTx(signerParams);
      return {
        instance: this.at(result.contractAddress),
        groupIndex: result.fromGroup,
        contractId: result.contractId,
        contractAddress: result.contractAddress,
        unsignedTx: result.unsignedTx,
        txId: result.txId,
        signature: result.signature,
        gasAmount: result.gasAmount,
        gasPrice: result.gasPrice,
      };
    }

    at(address: string): AddInstance {
      return new AddInstance(address);
    }
  }

  // This is used for testing contract functions
  export function stateForTest(
    initFields: Fields,
    asset?: Asset,
    address?: string
  ): ContractState {
    const newAsset = {
      alphAmount: asset?.alphAmount ?? ONE_ALPH,
      tokens: asset?.tokens,
    };
    return Add.contract.toState(initFields, newAsset, address);
  }

  export async function testAddMethod(
    args: { array: [bigint, bigint] },
    initFields: Fields,
    testParams?: {
      group?: number;
      address?: string;
      initialAsset?: Asset;
      existingContracts?: ContractState[];
      inputAssets?: InputAsset[];
    }
  ): Promise<
    Omit<TestContractResult, "returns"> & { returns: [bigint, bigint] }
  > {
    const initialAsset = {
      alphAmount: testParams?.initialAsset?.alphAmount ?? ONE_ALPH,
      tokens: testParams?.initialAsset?.tokens,
    };
    const _testParams = {
      ...testParams,
      testMethodIndex: 0,
      testArgs: args,
      initialFields: initFields,
      initialAsset: initialAsset,
    };
    const testResult = await contract.testPublicMethod("add", _testParams);
    const testReturns = testResult.returns as [[bigint, bigint]];
    return {
      ...testResult,
      returns: testReturns[0],
    };
  }

  export async function testAddPrivateMethod(
    args: { array: [bigint, bigint] },
    initFields: Fields,
    testParams?: {
      group?: number;
      address?: string;
      initialAsset?: Asset;
      existingContracts?: ContractState[];
      inputAssets?: InputAsset[];
    }
  ): Promise<
    Omit<TestContractResult, "returns"> & { returns: [bigint, bigint] }
  > {
    const initialAsset = {
      alphAmount: testParams?.initialAsset?.alphAmount ?? ONE_ALPH,
      tokens: testParams?.initialAsset?.tokens,
    };
    const _testParams = {
      ...testParams,
      testMethodIndex: 1,
      testArgs: args,
      initialFields: initFields,
      initialAsset: initialAsset,
    };
    const testResult = await contract.testPrivateMethod(
      "addPrivate",
      _testParams
    );
    const testReturns = testResult.returns as [[bigint, bigint]];
    return {
      ...testResult,
      returns: testReturns[0],
    };
  }

  export const contract = Contract.fromJson(AddContractJson);
  export const factory = new Factory(contract);
}

export class AddInstance {
  readonly address: Address;
  readonly contractId: string;
  readonly groupIndex: number;

  constructor(address: Address) {
    this.address = address;
    this.contractId = binToHex(contractIdFromAddress(address));
    this.groupIndex = groupOfAddress(address);
  }

  async fetchState(): Promise<Add.State> {
    const state = await Add.contract.fetchState(this.address, this.groupIndex);
    return {
      ...state,
      sub: state.fields["sub"] as HexString,
      result: state.fields["result"] as bigint,
    };
  }

  private decodeAddEvent(event: node.ContractEvent): Add.AddEvent {
    if (event.eventIndex !== 0) {
      throw new Error(
        "Invalid event index: " + event.eventIndex + ", expected: 0"
      );
    }
    const fields = fromApiVals(event.fields, ["x", "y"], ["U256", "U256"]);
    return {
      blockHash: event.blockHash,
      txId: event.txId,
      x: fields["x"] as bigint,
      y: fields["y"] as bigint,
      eventIndex: event.eventIndex,
    };
  }

  subscribeAddEvent(
    options: SubscribeOptions<Add.AddEvent>,
    fromCount?: number
  ): EventSubscription {
    const messageCallback = (event: node.ContractEvent): Promise<void> => {
      if (event.eventIndex !== 0) {
        return Promise.resolve();
      }
      return options.messageCallback(this.decodeAddEvent(event));
    };

    const errorCallback = (
      err: any,
      subscription: Subscription<node.ContractEvent>
    ): Promise<void> => {
      return options.errorCallback(
        err,
        subscription as unknown as Subscription<Add.AddEvent>
      );
    };
    const opt: SubscribeOptions<node.ContractEvent> = {
      pollingInterval: options.pollingInterval,
      messageCallback: messageCallback,
      errorCallback: errorCallback,
    };
    return subscribeToEvents(opt, this.address, fromCount);
  }

  private decodeAdd1Event(event: node.ContractEvent): Add.Add1Event {
    if (event.eventIndex !== 1) {
      throw new Error(
        "Invalid event index: " + event.eventIndex + ", expected: 1"
      );
    }
    const fields = fromApiVals(event.fields, ["a", "b"], ["U256", "U256"]);
    return {
      blockHash: event.blockHash,
      txId: event.txId,
      a: fields["a"] as bigint,
      b: fields["b"] as bigint,
      eventIndex: event.eventIndex,
    };
  }

  subscribeAdd1Event(
    options: SubscribeOptions<Add.Add1Event>,
    fromCount?: number
  ): EventSubscription {
    const messageCallback = (event: node.ContractEvent): Promise<void> => {
      if (event.eventIndex !== 1) {
        return Promise.resolve();
      }
      return options.messageCallback(this.decodeAdd1Event(event));
    };

    const errorCallback = (
      err: any,
      subscription: Subscription<node.ContractEvent>
    ): Promise<void> => {
      return options.errorCallback(
        err,
        subscription as unknown as Subscription<Add.Add1Event>
      );
    };
    const opt: SubscribeOptions<node.ContractEvent> = {
      pollingInterval: options.pollingInterval,
      messageCallback: messageCallback,
      errorCallback: errorCallback,
    };
    return subscribeToEvents(opt, this.address, fromCount);
  }

  subscribeEvents(
    options: SubscribeOptions<Add.AddEvent | Add.Add1Event>,
    fromCount?: number
  ): EventSubscription {
    const messageCallback = (event: node.ContractEvent): Promise<void> => {
      switch (event.eventIndex) {
        case 0: {
          return options.messageCallback(this.decodeAddEvent(event));
        }

        case 1: {
          return options.messageCallback(this.decodeAdd1Event(event));
        }

        default:
          throw new Error("Invalid event index: " + event.eventIndex);
      }
    };

    const errorCallback = (
      err: any,
      subscription: Subscription<node.ContractEvent>
    ): Promise<void> => {
      return options.errorCallback(
        err,
        subscription as unknown as Subscription<Add.AddEvent | Add.Add1Event>
      );
    };
    const opt: SubscribeOptions<node.ContractEvent> = {
      pollingInterval: options.pollingInterval,
      messageCallback: messageCallback,
      errorCallback: errorCallback,
    };
    return subscribeToEvents(opt, this.address, fromCount);
  }

  async callAddMethod(
    args: { array: [bigint, bigint] },
    callParams?: {
      worldStateBlockHash?: string;
      txId?: string;
      existingContracts?: string[];
      inputAssets?: node.TestInputAsset[];
    }
  ): Promise<[bigint, bigint]> {
    const callResult = await web3
      .getCurrentNodeProvider()
      .contracts.postContractsCallContract({
        group: this.groupIndex,
        worldStateBlockHash: callParams?.worldStateBlockHash,
        txId: callParams?.txId,
        address: this.address,
        methodIndex: 0,
        args: toApiVals({ array: args.array }, ["array"], ["[U256;2]"]),
        existingContracts: callParams?.existingContracts,
        inputAssets: callParams?.inputAssets,
      });
    return fromApiArray(callResult.returns, ["[U256;2]"])[0] as [
      bigint,
      bigint
    ];
  }
}
