/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const AssertError = BigInt("3");
export const A = BigInt("-3");
export const B = "1DrDyTr9RpRsQnDnXo2YRiPzPW4ooHX5LLoqXrqfMrpQH";
export const ConstantTrue = true;
export const ConstantFalse = false;
export const Numbers = {
  A: BigInt("0"),
  B: BigInt("1"),
  C: BigInt(
    "115792089237316195423570985008687907853269984665640564039457584007913129639935"
  ),
};
export const Addresses = {
  A: "1DrDyTr9RpRsQnDnXo2YRiPzPW4ooHX5LLoqXrqfMrpQH",
  B: "14UAjZ3qcmEVKdTo84Kwf4RprTQi86w2TefnnGFjov9xF",
};
export const ByteVecs = { A: "00", B: "11" };
export const ErrorCodes = {
  IncorrectTokenIndex: BigInt("0"),
  NFTNotFound: BigInt("1"),
  NFTNotPartOfCollection: BigInt("2"),
  CollectionOwnerAllowedOnly: BigInt("3"),
};
