/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractFactory } from "@alephium/web3";
import {
  Add,
  Greeter,
  NFTCollectionTest,
  NFTTest,
  Sub,
  Assert,
  Debug,
  MetaData,
  Warnings,
  FakeTokenTest,
  TokenTest,
} from ".";

  const contracts = (): ContractFactory<any>[] => [
    Add,
    Greeter,
    NFTCollectionTest,
    NFTTest,
    Sub,
    Assert,
    Debug,
    MetaData,
    Warnings,
    FakeTokenTest,
    TokenTest,
  ];

export const getContractByCodeHash = (codeHash: string): Contract => {
  // console.log(contracts)
  const c = contracts().find(
    (c) => {
      console.log(c)
      return c.contract.codeHash === codeHash || c.contract.codeHashDebug === codeHash
    }
  );
  if (c === undefined) {
    throw new Error("Unknown code with code hash: " + codeHash);
  }
  return c.contract;
}
