/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractFactory } from "@alephium/web3";
import {
  Add,
  Assert,
  Debug,
  DeprecatedNFTTest1,
  DeprecatedNFTTest2,
  DeprecatedNFTTest3,
  DeprecatedNFTTest4,
  DeprecatedNFTTest5,
  DeprecatedNFTTest6,
  DeprecatedNFTTest7,
  FakeTokenTest,
  Greeter,
  MapTest,
  MetaData,
  NFTCollectionTest,
  NFTCollectionWithRoyaltyTest,
  NFTTest,
  NFTTestStd,
  OwnerOnly,
  Sub,
  TokenTest,
  TokenTestStd,
  Transact,
  UserAccount,
  Warnings,
  WrongNFTTest,
} from ".";

let contracts: ContractFactory<any>[] | undefined = undefined;
export function getContractByCodeHash(codeHash: string): Contract {
  if (contracts === undefined) {
    contracts = [
      Add,
      Assert,
      Debug,
      DeprecatedNFTTest1,
      DeprecatedNFTTest2,
      DeprecatedNFTTest3,
      DeprecatedNFTTest4,
      DeprecatedNFTTest5,
      DeprecatedNFTTest6,
      DeprecatedNFTTest7,
      FakeTokenTest,
      Greeter,
      MapTest,
      MetaData,
      NFTCollectionTest,
      NFTCollectionWithRoyaltyTest,
      NFTTest,
      NFTTestStd,
      OwnerOnly,
      Sub,
      TokenTest,
      TokenTestStd,
      Transact,
      UserAccount,
      Warnings,
      WrongNFTTest,
    ];
  }
  const c = contracts.find((c) => c.contract.hasCodeHash(codeHash));
  if (c === undefined) {
    throw new Error("Unknown code with code hash: " + codeHash);
  }
  return c.contract;
}
