/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract } from "@alephium/web3";
import {
  AddStruct1,
  AddStruct2,
  Balances,
  MapValue,
  TokenBalance,
  AllStructs,
} from "./types";
import { default as AddContractJson } from "../add/Add.ral.json";
import { default as AssertContractJson } from "../test/Assert.ral.json";
import { default as DebugContractJson } from "../test/Debug.ral.json";
import { default as DeprecatedNFTTest1ContractJson } from "../nft/DeprecatedNFTTest1.ral.json";
import { default as DeprecatedNFTTest2ContractJson } from "../nft/DeprecatedNFTTest2.ral.json";
import { default as DeprecatedNFTTest3ContractJson } from "../nft/DeprecatedNFTTest3.ral.json";
import { default as DeprecatedNFTTest4ContractJson } from "../nft/DeprecatedNFTTest4.ral.json";
import { default as DeprecatedNFTTest5ContractJson } from "../nft/DeprecatedNFTTest5.ral.json";
import { default as DeprecatedNFTTest6ContractJson } from "../nft/DeprecatedNFTTest6.ral.json";
import { default as DeprecatedNFTTest7ContractJson } from "../nft/DeprecatedNFTTest7.ral.json";
import { default as FakeTokenTestContractJson } from "../token/FakeTokenTest.ral.json";
import { default as GreeterContractJson } from "../greeter/Greeter.ral.json";
import { default as MapTestContractJson } from "../test/MapTest.ral.json";
import { default as MapTestWrapperContractJson } from "../test/MapTestWrapper.ral.json";
import { default as MetaDataContractJson } from "../test/MetaData.ral.json";
import { default as NFTCollectionTestContractJson } from "../nft/NFTCollectionTest.ral.json";
import { default as NFTCollectionWithRoyaltyTestContractJson } from "../nft/NFTCollectionWithRoyaltyTest.ral.json";
import { default as NFTTestContractJson } from "../nft/NFTTest.ral.json";
import { default as NFTTestStdContractJson } from "../nft/NFTTestStd.ral.json";
import { default as OwnerOnlyContractJson } from "../test/OwnerOnly.ral.json";
import { default as SubContractJson } from "../sub/Sub.ral.json";
import { default as TokenTestContractJson } from "../token/TokenTest.ral.json";
import { default as TokenTestStdContractJson } from "../token/TokenTestStd.ral.json";
import { default as TransactContractJson } from "../test/Transact.ral.json";
import { default as UserAccountContractJson } from "../test/UserAccount.ral.json";
import { default as WarningsContractJson } from "../test/Warnings.ral.json";
import { default as WrongNFTTestContractJson } from "../nft/WrongNFTTest.ral.json";
export const AddContractArtifact: Contract = Contract.fromJson(
  AddContractJson,
  "=12-2+5c=2-2+81=3-1+e=2-2+bc=83-1+97e010a61646450726976617465=266",
  "c46db1ae7bae8b332c115869126eb1402bc71574925608a2adcea3cf7b9f8e7e",
  AllStructs
);

export const AssertContractArtifact: Contract = Contract.fromJson(
  AssertContractJson,
  "",
  "46dc5e3835be6551dacbf81565912ec67575aa77522312ceed88472817735d6b",
  AllStructs
);

export const DebugContractArtifact: Contract = Contract.fromJson(
  DebugContractJson,
  "=4-2+18=11-1+3=10+ca7e020748656c6c6f2c200121",
  "eb4209d8f543d9f623d72578f7ed9b271d62cf396dcce42d10f5e68dba3cecd3",
  AllStructs
);

export const DeprecatedNFTTest1ContractArtifact: Contract = Contract.fromJson(
  DeprecatedNFTTest1ContractJson,
  "",
  "cc6928c9c6777077abcb5b9c4f7c5d620d6cae07ec6f00f5e8b0efe6a7b913c4",
  AllStructs
);

export const DeprecatedNFTTest2ContractArtifact: Contract = Contract.fromJson(
  DeprecatedNFTTest2ContractJson,
  "",
  "ade9aee476ee752050a1e9e1b19039f05261cb3f53941152617174faf9eae572",
  AllStructs
);

export const DeprecatedNFTTest3ContractArtifact: Contract = Contract.fromJson(
  DeprecatedNFTTest3ContractJson,
  "",
  "465bc3739cd1649e58e0470971bd2fabf21363ab9fc2c15052fb2440dd06ada5",
  AllStructs
);

export const DeprecatedNFTTest4ContractArtifact: Contract = Contract.fromJson(
  DeprecatedNFTTest4ContractJson,
  "",
  "a5de0fa0b3580303ac63423f09ce5ed95fccbf789679b32130a53c26fef182e9",
  AllStructs
);

export const DeprecatedNFTTest5ContractArtifact: Contract = Contract.fromJson(
  DeprecatedNFTTest5ContractJson,
  "",
  "8b1374f39db98c485af3dd05d0b0ce861e9528f290ca9dc0d7108e8b48b50161",
  AllStructs
);

export const DeprecatedNFTTest6ContractArtifact: Contract = Contract.fromJson(
  DeprecatedNFTTest6ContractJson,
  "",
  "8bc0d39f0607d4a771ec70ae1057b71dbcde404177cb3b25fd7d93d553a2b8cd",
  AllStructs
);

export const DeprecatedNFTTest7ContractArtifact: Contract = Contract.fromJson(
  DeprecatedNFTTest7ContractJson,
  "",
  "b95c9acf088b090f5d9d34f28ab079cf22b9e53af8ae6864113c71172231ef4c",
  AllStructs
);

export const FakeTokenTestContractArtifact: Contract = Contract.fromJson(
  FakeTokenTestContractJson,
  "",
  "52f971cb44d54a5353e94dc8db991d2726f76760af782e79bd8a66a9b5b294b7",
  AllStructs
);

export const GreeterContractArtifact: Contract = Contract.fromJson(
  GreeterContractJson,
  "",
  "4bbf82c83dcb0a3df905c290fbc12a19ce5160a7b655c1a347913481da12d747",
  AllStructs
);

export const MapTestContractArtifact: Contract = Contract.fromJson(
  MapTestContractJson,
  "=6-2+a8=1-3+128=2-2+ea=1+2=1-2+7=10-2+4025=50+7a7e0214696e73657274206174206d617020706174683a2000=56+7a7e0214696e73657274206174206d617020706174683a2000=54+7a7e0214696e73657274206174206d617020706174683a2000=280-2+33=124+7a7e021472656d6f7665206174206d617020706174683a2000=46+7a7e021472656d6f7665206174206d617020706174683a2000=48+7a7e021472656d6f7665206174206d617020706174683a2000=96",
  "31aed0ff7b29f2cbc2d8360a83f31af4e9db00f0084a7406bd84b7745181373d",
  AllStructs
);

export const MapTestWrapperContractArtifact: Contract = Contract.fromJson(
  MapTestWrapperContractJson,
  "",
  "1d525d3e4cbd1c8f4c0431bf6881e888eeebae012a14532530097f62dd766e9a",
  AllStructs
);

export const MetaDataContractArtifact: Contract = Contract.fromJson(
  MetaDataContractJson,
  "",
  "5b113459525557465f1cc5aeee453dfd5823d1a6094372cee6067f7466b40896",
  AllStructs
);

export const NFTCollectionTestContractArtifact: Contract = Contract.fromJson(
  NFTCollectionTestContractJson,
  "",
  "087f9292bb326a4d39a6fac09928cb25edf2837718f830f3a166a937f8724779",
  AllStructs
);

export const NFTCollectionWithRoyaltyTestContractArtifact: Contract =
  Contract.fromJson(
    NFTCollectionWithRoyaltyTestContractJson,
    "",
    "3b64d5e360566a4e4f568f773536a3ea74e66d12231aa44f19d2214ba87b38d6",
    AllStructs
  );

export const NFTTestContractArtifact: Contract = Contract.fromJson(
  NFTTestContractJson,
  "",
  "4897086210869e612d82995b765a447c5319a55a56e8a0c3c07b4d9ca81e15b1",
  AllStructs
);

export const NFTTestStdContractArtifact: Contract = Contract.fromJson(
  NFTTestStdContractJson,
  "",
  "b7ff3fa8dfacc7ae5edbabd6573d0699dffc5a0f07ad14023f682a201b7bce55",
  AllStructs
);

export const OwnerOnlyContractArtifact: Contract = Contract.fromJson(
  OwnerOnlyContractJson,
  "",
  "c8ecfd7b7e1f3d0169d80e0abb59702516eeff301d47e0e7be70a631bd9414ca",
  AllStructs
);

export const SubContractArtifact: Contract = Contract.fromJson(
  SubContractJson,
  "",
  "3461ebfaca02ad0a3f587a5b67a461c0cbd82d14261407b1d9277ed4ad129234",
  AllStructs
);

export const TokenTestContractArtifact: Contract = Contract.fromJson(
  TokenTestContractJson,
  "",
  "a2800413eb2c5c23d48068db23df5f8eeaba04653e12c8ed59d589720d96dadd",
  AllStructs
);

export const TokenTestStdContractArtifact: Contract = Contract.fromJson(
  TokenTestStdContractJson,
  "",
  "4aa5c769148cada8eeb1cd3791f6e793ed92009ac79ebb64dc79d4d7f2969c8b",
  AllStructs
);

export const TransactContractArtifact: Contract = Contract.fromJson(
  TransactContractJson,
  "",
  "85e3e9a803741af8e92bd43b1b07cde53f39b86cab0ef1a85bab12b10d691b55",
  AllStructs
);

export const UserAccountContractArtifact: Contract = Contract.fromJson(
  UserAccountContractJson,
  "",
  "4e9f7eac1b76eaa2268b5af6ebb5640252892dc170aad6c1ee7b639131a55816",
  AllStructs
);

export const WarningsContractArtifact: Contract = Contract.fromJson(
  WarningsContractJson,
  "",
  "873e095edb39cdb4b11b1157003daeacad06d259a938cd270e22b8e89b75feea",
  AllStructs
);

export const WrongNFTTestContractArtifact: Contract = Contract.fromJson(
  WrongNFTTestContractJson,
  "",
  "7dd2ed643a98b2a1a52a9b9e536fcdae60d961b583b8109f777d846bfdfcae8d",
  AllStructs
);

let contractArtifacts: Contract[] | undefined = undefined;
export function getContractByCodeHash(codeHash: string): Contract {
  if (contractArtifacts === undefined) {
    contractArtifacts = [
      AddContractArtifact,
      AssertContractArtifact,
      DebugContractArtifact,
      DeprecatedNFTTest1ContractArtifact,
      DeprecatedNFTTest2ContractArtifact,
      DeprecatedNFTTest3ContractArtifact,
      DeprecatedNFTTest4ContractArtifact,
      DeprecatedNFTTest5ContractArtifact,
      DeprecatedNFTTest6ContractArtifact,
      DeprecatedNFTTest7ContractArtifact,
      FakeTokenTestContractArtifact,
      GreeterContractArtifact,
      MapTestContractArtifact,
      MapTestWrapperContractArtifact,
      MetaDataContractArtifact,
      NFTCollectionTestContractArtifact,
      NFTCollectionWithRoyaltyTestContractArtifact,
      NFTTestContractArtifact,
      NFTTestStdContractArtifact,
      OwnerOnlyContractArtifact,
      SubContractArtifact,
      TokenTestContractArtifact,
      TokenTestStdContractArtifact,
      TransactContractArtifact,
      UserAccountContractArtifact,
      WarningsContractArtifact,
      WrongNFTTestContractArtifact,
    ];
  }
  const c = contractArtifacts.find((c) => c.hasCodeHash(codeHash));
  if (c === undefined) {
    throw new Error("Unknown code with code hash: " + codeHash);
  }
  return c;
}
