/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as FakeTokenTestContractJson } from "../token/FakeTokenTest.ral.json";
import { getContractByCodeHash } from "./contracts";
import { Balances, MapValue, TokenBalance, AllStructs } from "./types";

// Custom types for the contract
export namespace FakeTokenTestTypes {
  export type Fields = {
    a: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  FakeTokenTestInstance,
  FakeTokenTestTypes.Fields
> {
  encodeFields(fields: FakeTokenTestTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as FakeTokenTestTypes.Fields;
  }

  at(address: string): FakeTokenTestInstance {
    return new FakeTokenTestInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<FakeTokenTestTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<FakeTokenTestTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<FakeTokenTestTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<FakeTokenTestTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    foo: async (
      params: Omit<
        TestContractParamsWithoutMaps<FakeTokenTestTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "foo", params);
    },
  };
}

// Use this object to test and deploy the contract
export const FakeTokenTest = new Factory(
  Contract.fromJson(
    FakeTokenTestContractJson,
    "",
    "52f971cb44d54a5353e94dc8db991d2726f76760af782e79bd8a66a9b5b294b7",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class FakeTokenTestInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FakeTokenTestTypes.State> {
    return fetchContractState(FakeTokenTest, this);
  }

  methods = {
    getSymbol: async (
      params?: FakeTokenTestTypes.CallMethodParams<"getSymbol">
    ): Promise<FakeTokenTestTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        FakeTokenTest,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: FakeTokenTestTypes.CallMethodParams<"getName">
    ): Promise<FakeTokenTestTypes.CallMethodResult<"getName">> => {
      return callMethod(
        FakeTokenTest,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: FakeTokenTestTypes.CallMethodParams<"getDecimals">
    ): Promise<FakeTokenTestTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        FakeTokenTest,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: FakeTokenTestTypes.CallMethodParams<"getTotalSupply">
    ): Promise<FakeTokenTestTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        FakeTokenTest,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends FakeTokenTestTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FakeTokenTestTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      FakeTokenTest,
      this,
      calls,
      getContractByCodeHash
    )) as FakeTokenTestTypes.MultiCallResults<Calls>;
  }
}
