/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as MapTestSubContractJson } from "../test/MapTestSub.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  AddStruct1,
  AddStruct2,
  Balances,
  MapValue,
  TokenBalance,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace MapTestSubTypes {
  export type Fields = {
    mapTestTemplateId: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    init: {
      params: CallContractParams<{ caller: Address; value: MapValue }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    init: {
      params: SignExecuteContractMethodParams<{
        caller: Address;
        value: MapValue;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  MapTestSubInstance,
  MapTestSubTypes.Fields
> {
  encodeFields(fields: MapTestSubTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): MapTestSubInstance {
    return new MapTestSubInstance(address);
  }

  tests = {
    init: async (
      params: TestContractParamsWithoutMaps<
        MapTestSubTypes.Fields,
        { caller: Address; value: MapValue }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "init", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: MapTestSubTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const MapTestSub = new Factory(
  Contract.fromJson(
    MapTestSubContractJson,
    "",
    "0d30814a6068aab2c3da0de073191fa643d50d7bdc7c0068805056c511bec720",
    AllStructs
  )
);
registerContract(MapTestSub);

// Use this class to interact with the blockchain
export class MapTestSubInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<MapTestSubTypes.State> {
    return fetchContractState(MapTestSub, this);
  }

  view = {
    init: async (
      params: MapTestSubTypes.CallMethodParams<"init">
    ): Promise<MapTestSubTypes.CallMethodResult<"init">> => {
      return callMethod(
        MapTestSub,
        this,
        "init",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    init: async (
      params: MapTestSubTypes.SignExecuteMethodParams<"init">
    ): Promise<MapTestSubTypes.SignExecuteMethodResult<"init">> => {
      return signExecuteMethod(MapTestSub, this, "init", params);
    },
  };
}
