/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  web3,
  SignerProvider,
  Address,
  DeployContractParams,
  DeployContractResult,
  Contract,
  ContractState,
  node,
  binToHex,
  TestContractResult,
  Asset,
  HexString,
  ContractFactory,
  contractIdFromAddress,
  ONE_ALPH,
  groupOfAddress,
  fromApiVals,
  subscribeToEvents,
  SubscribeOptions,
  Subscription,
  EventSubscription,
  randomTxId,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeEventsFromContract,
  decodeContractCreatedEvent,
  decodeContractDestroyedEvent,
  ContractCreatedEvent,
  ContractDestroyedEvent,
} from "@alephium/web3";
import { default as MetaDataContractJson } from "../test/metadata.ral.json";

export namespace MetaData {
  export type State = Omit<ContractState<any>, "fields">;

  export class Factory extends ContractFactory<MetaDataInstance, {}> {
    constructor(contract: Contract) {
      super(contract);
    }

    at(address: string): MetaDataInstance {
      return new MetaDataInstance(address);
    }
  }

  // This is used for testing contract functions
  export function stateForTest(
    asset?: Asset,
    address?: string
  ): ContractState<{}> {
    const newAsset = {
      alphAmount: asset?.alphAmount ?? ONE_ALPH,
      tokens: asset?.tokens,
    };
    return MetaData.contract.toState({}, newAsset, address);
  }

  export async function testFooMethod(
    params?: Omit<TestContractParams<{}, {}>, "testArgs" | "initialFields">
  ): Promise<Omit<TestContractResult, "returns">> {
    const txId = params?.txId ?? randomTxId();
    const apiParams = MetaData.contract.toApiTestContractParams("foo", {
      ...params,
      txId: txId,
      testArgs: {},
      initialFields: {},
    });
    const apiResult = await web3
      .getCurrentNodeProvider()
      .contracts.postContractsTestContract(apiParams);
    const testResult = MetaData.contract.fromApiTestContractResult(
      0,
      apiResult,
      txId
    );
    MetaData.contract.printDebugMessages("foo", testResult.debugMessages);

    return {
      ...testResult,
    };
  }

  export async function testBarMethod(
    params?: Omit<TestContractParams<{}, {}>, "testArgs" | "initialFields">
  ): Promise<Omit<TestContractResult, "returns">> {
    const txId = params?.txId ?? randomTxId();
    const apiParams = MetaData.contract.toApiTestContractParams("bar", {
      ...params,
      txId: txId,
      testArgs: {},
      initialFields: {},
    });
    const apiResult = await web3
      .getCurrentNodeProvider()
      .contracts.postContractsTestContract(apiParams);
    const testResult = MetaData.contract.fromApiTestContractResult(
      1,
      apiResult,
      txId
    );
    MetaData.contract.printDebugMessages("bar", testResult.debugMessages);

    return {
      ...testResult,
    };
  }

  export async function testBazMethod(
    params?: Omit<TestContractParams<{}, {}>, "testArgs" | "initialFields">
  ): Promise<Omit<TestContractResult, "returns">> {
    const txId = params?.txId ?? randomTxId();
    const apiParams = MetaData.contract.toApiTestContractParams("baz", {
      ...params,
      txId: txId,
      testArgs: {},
      initialFields: {},
    });
    const apiResult = await web3
      .getCurrentNodeProvider()
      .contracts.postContractsTestContract(apiParams);
    const testResult = MetaData.contract.fromApiTestContractResult(
      2,
      apiResult,
      txId
    );
    MetaData.contract.printDebugMessages("baz", testResult.debugMessages);

    return {
      ...testResult,
    };
  }

  export const contract = Contract.fromJson(
    MetaDataContractJson,
    "",
    "cade0de390b8e15960b263ac35aa013cb84f844bce6e3e53e6bfe2cc9166623f"
  );
  export const factory = new Factory(contract);
}

export class MetaDataInstance {
  readonly address: Address;
  readonly contractId: string;
  readonly groupIndex: number;

  constructor(address: Address) {
    this.address = address;
    this.contractId = binToHex(contractIdFromAddress(address));
    this.groupIndex = groupOfAddress(address);
  }

  async fetchState(): Promise<MetaData.State> {
    const contractState = await web3
      .getCurrentNodeProvider()
      .contracts.getContractsAddressState(this.address, {
        group: this.groupIndex,
      });
    const state = MetaData.contract.fromApiContractState(contractState);
    return {
      ...state,
    };
  }

  subscribeContractCreatedEvent(
    options: SubscribeOptions<ContractCreatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeEventsFromContract(
      options,
      this.address,
      -1,
      (event) => {
        return {
          ...decodeContractCreatedEvent(event),
          contractAddress: this.address,
        };
      },
      fromCount
    );
  }

  subscribeContractDestroyedEvent(
    options: SubscribeOptions<ContractDestroyedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeEventsFromContract(
      options,
      this.address,
      -2,
      (event) => {
        return {
          ...decodeContractDestroyedEvent(event),
          contractAddress: this.address,
        };
      },
      fromCount
    );
  }

  subscribeEvents(
    options: SubscribeOptions<ContractCreatedEvent | ContractDestroyedEvent>,
    fromCount?: number
  ): EventSubscription {
    const messageCallback = (event: node.ContractEvent): Promise<void> => {
      switch (event.eventIndex) {
        case -1: {
          return options.messageCallback({
            ...decodeContractCreatedEvent(event),
            contractAddress: this.address,
          });
        }

        case -2: {
          return options.messageCallback({
            ...decodeContractDestroyedEvent(event),
            contractAddress: this.address,
          });
        }

        default:
          throw new Error("Invalid event index: " + event.eventIndex);
      }
    };
    const errorCallback = (
      err: any,
      subscription: Subscription<node.ContractEvent>
    ): Promise<void> => {
      return options.errorCallback(
        err,
        subscription as unknown as Subscription<
          ContractCreatedEvent | ContractDestroyedEvent
        >
      );
    };
    const opt: SubscribeOptions<node.ContractEvent> = {
      pollingInterval: options.pollingInterval,
      messageCallback: messageCallback,
      errorCallback: errorCallback,
    };
    return subscribeToEvents(opt, this.address, fromCount);
  }
}
