/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as OwnerOnlyContractJson } from "../test/OwnerOnly.ral.json";
import { getContractByCodeHash } from "./contracts";
import {
  AddStruct1,
  AddStruct2,
  Balances,
  MapValue,
  TokenBalance,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace OwnerOnlyTypes {
  export type Fields = {
    owner: Address;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    testOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> =
    Callss["length"] extends 1
      ? MultiCallResults<Callss[0]>
      : { [index in keyof Callss]: MultiCallResults<Callss[index]> };

  export interface SignExecuteMethodTable {
    testOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  OwnerOnlyInstance,
  OwnerOnlyTypes.Fields
> {
  encodeFields(fields: OwnerOnlyTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): OwnerOnlyInstance {
    return new OwnerOnlyInstance(address);
  }

  tests = {
    testOwner: async (
      params: Omit<
        TestContractParamsWithoutMaps<OwnerOnlyTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "testOwner", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const OwnerOnly = new Factory(
  Contract.fromJson(
    OwnerOnlyContractJson,
    "",
    "c8ecfd7b7e1f3d0169d80e0abb59702516eeff301d47e0e7be70a631bd9414ca",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class OwnerOnlyInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<OwnerOnlyTypes.State> {
    return fetchContractState(OwnerOnly, this);
  }

  view = {
    testOwner: async (
      params?: OwnerOnlyTypes.CallMethodParams<"testOwner">
    ): Promise<OwnerOnlyTypes.CallMethodResult<"testOwner">> => {
      return callMethod(
        OwnerOnly,
        this,
        "testOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    testOwner: async (
      params: OwnerOnlyTypes.SignExecuteMethodParams<"testOwner">
    ): Promise<OwnerOnlyTypes.SignExecuteMethodResult<"testOwner">> => {
      return signExecuteMethod(OwnerOnly, this, "testOwner", params);
    },
  };
}
