/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Address, HexString, Val, Struct } from "@alephium/web3";
import { default as allStructsJson } from "../structs.ral.json";
export const AllStructs = allStructsJson.map((json) => Struct.fromJson(json));
export interface Balances extends Record<string, Val> {
  totalAmount: bigint;
  tokens: [TokenBalance, TokenBalance];
}
export interface MapValue extends Record<string, Val> {
  id: bigint;
  balance: bigint;
}
export interface TokenBalance extends Record<string, Val> {
  tokenId: HexString;
  amount: bigint;
}
