/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
  SignExecuteScriptTxResult
} from "@alephium/web3";
import { default as MainScriptJson } from "../Main.ral.json";

export namespace Main {
  export async function execute(
    params: ExecuteScriptParams<{ greeterContractId: HexString }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(params);
    return (await params.signer.signAndSubmitExecuteScriptTx(signerParams)) as SignExecuteScriptTxResult;
  }

  export const script = Script.fromJson(MainScriptJson);
}
