name: Njsscan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '15 23 * * 0'

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      - name: Checkout the code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Use Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 20

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@231750a435d85095d33be7d192d52ec650625146 # v9
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@d3ced5c96c16c4332e2a61eb6f3649d6f1b20bb8 # v3.31.5
        with:
          sarif_file: results.sarif
